import "~/styles/globals.css";

import { Outfit } from "next/font/google";
import TopNav from "./_components/TopNav";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-geist-sans",
});

export const metadata = {
  title: "Streaming App",
  description: "Generated by Okori",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${outfit.variable} `}>
      <body className=" bg-tertiary-100 flex h-svh max-h-screen w-full flex-row">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
