import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { AppContextProvider } from "./Context/state";

import { Outfit } from "next/font/google";
import TopNav from "./_components/TopNav";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-geist-sans",
});

export const metadata = {
  title: "Streaming App",
  description: "Generated by Okori",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${outfit.variable} `}>
        <AppContextProvider>
          <body className=" relative flex h-svh max-h-screen w-screen flex-row bg-tertiary-100">
            <TopNav />
            {children}
          </body>
        </AppContextProvider>
      </html>
    </ClerkProvider>
  );
}
